# Generated by Django 5.1.1 on 2024-09-15 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Diets",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Diet",
                "verbose_name_plural": "Diets",
            },
        ),
        migrations.CreateModel(
            name="Exercises",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("demo_url_short", models.URLField()),
                ("demo_url_detail", models.URLField()),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("Beginner", "Beginner"),
                            ("Intermediate", "Intermediate"),
                            ("Hard", "Hard"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "muscle_group",
                    models.CharField(
                        choices=[
                            ("Back", "Back"),
                            ("Abdominal", "Abdominal"),
                            ("Legs", "Legs"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "equipment",
                    models.CharField(
                        choices=[("Dumbbell", "Dumbbell"), ("Weights", "Weights")],
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Exercise",
                "verbose_name_plural": "Exercises",
            },
        ),
        migrations.CreateModel(
            name="Recipes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("carbs", models.FloatField()),
                ("fats", models.FloatField()),
                ("calories", models.FloatField()),
                ("proteins", models.FloatField()),
                ("sugar", models.FloatField()),
                ("description", models.TextField()),
                ("steps", models.TextField()),
                ("time", models.IntegerField()),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Recipe",
                "verbose_name_plural": "Recipes",
            },
        ),
        migrations.CreateModel(
            name="DietRecipes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "diet_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.diets"
                    ),
                ),
                (
                    "recipes_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.recipes"
                    ),
                ),
            ],
            options={
                "verbose_name": "Diet-recipe",
                "verbose_name_plural": "Diet-Recipes",
            },
        ),
        migrations.CreateModel(
            name="UserProfiles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("height", models.IntegerField()),
                ("weight", models.IntegerField()),
                ("age", models.IntegerField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")], max_length=50
                    ),
                ),
                (
                    "goals",
                    models.CharField(
                        choices=[
                            ("Gain Weight", "Gain Weight"),
                            ("Lose Weight", "Lose Weight"),
                            ("Gain Muscle", "Gain Muscle"),
                            ("Maintain", "Maintain"),
                        ],
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="diets",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.userprofiles"
            ),
        ),
        migrations.CreateModel(
            name="Workouts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.userprofiles",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workout",
                "verbose_name_plural": "Workouts",
            },
        ),
        migrations.CreateModel(
            name="WorkoutExercises",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reps", models.IntegerField()),
                ("sets", models.IntegerField()),
                (
                    "exercise_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.exercises"
                    ),
                ),
                (
                    "workout_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.workouts"
                    ),
                ),
            ],
            options={
                "verbose_name": "Workout-Exercise",
                "verbose_name_plural": "Workout-Exercises",
            },
        ),
    ]
