# Generated by Django 5.1.1 on 2024-09-15 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_diets_exercises_recipes_dietrecipes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={},
        ),
    ]
