# Generated by Django 5.1.1 on 2024-09-19 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_diets_exercises_recipes_dietrecipes_userprofiles_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('name_en_us', models.CharField(max_length=100)),
                ('include_in_api', models.BooleanField(default=False)),
                ('include_in_workout_generator', models.BooleanField(default=False)),
                ('display_order', models.IntegerField(default=0)),
                ('enable', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='category_images/')),
                ('mobile_icon', models.ImageField(blank=True, null=True, upload_to='category_icons/')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Difficulty',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('name_en_us', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='diets',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='workoutexercises',
            name='exercise_id',
        ),
        migrations.RemoveField(
            model_name='workoutexercises',
            name='workout_id',
        ),
        migrations.RemoveField(
            model_name='workouts',
            name='user_id',
        ),
        migrations.AlterModelOptions(
            name='userprofiles',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.CreateModel(
            name='Muscle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('name_en_us', models.CharField(max_length=100)),
                ('scientific_name', models.CharField(blank=True, max_length=100, null=True)),
                ('url_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('description_en_us', models.TextField(blank=True, null=True)),
                ('lft', models.IntegerField()),
                ('rght', models.IntegerField()),
                ('tree_id', models.IntegerField()),
                ('level', models.IntegerField()),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.muscle')),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('target_url_male', models.URLField(blank=True, null=True)),
                ('target_url_female', models.URLField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category')),
                ('difficulty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.difficulty')),
                ('muscles', models.ManyToManyField(to='api.muscle')),
            ],
        ),
        migrations.DeleteModel(
            name='DietRecipes',
        ),
        migrations.DeleteModel(
            name='Recipes',
        ),
        migrations.DeleteModel(
            name='Diets',
        ),
        migrations.DeleteModel(
            name='Exercises',
        ),
        migrations.DeleteModel(
            name='WorkoutExercises',
        ),
        migrations.DeleteModel(
            name='Workouts',
        ),
    ]
